In [26]:
import numpy as np
import pandas as pd
from scipy import stats

In [10]:
#Q1
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4, 5, 6],
                 [7, 8, 9]])
arr1 = arr1.reshape(1, 3)

result = np.concatenate((arr1, arr2), axis=0)
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Q2
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flat_arr = arr.flatten()

print(flat_arr)

[1 2 3 4 5 6]


In [11]:
#Q3
arr=np.array([1,2,3,4,5,6])
reverse= arr[::-1]
print(reverse)

[6 5 4 3 2 1]


In [23]:
#Q4
arr = np.array([[10, 25, 5, 40, 15],[20,30,45,69,67]])

print("Maximum value:", arr.max())
print("Minimum value:", arr.min())

rows, cols = arr.shape

print("Rows:", rows)
print("Columns:", cols)

for row in arr:
    for element in row:
        print(element, end=" ")

print("\nSpecific element:", arr[0, 1])

#Sum in 2D array
total = 0

for row in arr:
    for element in row:
        total += element

print("Sum =", total)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("\nAddition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Maximum value: 69
Minimum value: 5
Rows: 2
Columns: 5
10 25 5 40 15 20 30 45 69 67 
Specific element: 25
Sum = 326

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [33]:
#Q5
arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

for i in arr:
    for j in i:
        for k in j:
            print(k, end=" ")
print("\n")
#using nditer
for x in np.nditer(arr):
    print(x, end=" ")

1 2 3 4 5 6 7 8 

1 2 3 4 5 6 7 8 

In [30]:
#Q6
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([[7, 8, 9],
                 [1, 2, 3]])

# Combine arrays
combined = np.concatenate((arr1, arr2))

print("Combined Array:")
print(combined)

# Mean
mean_value = np.mean(combined)

# Median
median_value = np.median(combined)

# Mode
mode_value = stats.mode(combined, axis=None, keepdims=False)

print("\nMean =", mean_value)
print("Median =", median_value)
print("Mode =", mode_value.mode)

avg = (arr1 + arr2) / 2

print("Average Array:")
print(avg)

Combined Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]

Mean = 4.25
Median = 3.5
Mode = 1
Average Array:
[[4.  5.  6. ]
 [2.5 3.5 4.5]]
